### ISSUE TITLE
Not async?

### ISSUE THREAD

**Issue by carlosalvidrez** [Meteor-Community-Packages/meteor-roles#395]
**Describe the bug**

Meteor migration helper reports the server _roles method not being async.

`W20240516-13:25:36.457(-4)? (STDERR) Deprecated (Publication): _roles is not async, consider migrating now.
W20240516-13:25:36.457(-4)? (STDERR)   => at module (packages/alanning:roles/roles/roles_server.js:30:8)
`

**Expected behavior**

I assume the presence of the meteor migration helper package should NOT report the serve roles method being not async. 
https://github.com/jankapunkt/meteor-migration-helper

**Additional context**

Migrating to Meteor v3, using the latest version of this package.

**Comment by carlosalvidrez** [comment]
Another debug report that may be helpful, thanks!

`Deprecated: Collection.findOne needs to be migrated to findOneAsync in collection "roles"!
=> at Object._addUserToRole (packages/alanning:roles/roles/roles_common.js:463:31)`

**Comment by carlosalvidrez** [comment]
Not sure this is valid after all... now that I upgraded to v3, this doesn't happen anymore, thanks!
